CONSUMER_API_KEY='[paste your CONSUMER_API_KEY here]'
CONSUMER_API_SECRET='[paste your CONSUMER_API_SECRET here]'

ACCESS_TOKEN='[paste ACCESS_TOKEN here]'
ACCESS_TOKEN_SECRET='[paste your ACCESS_TOKEN_SECRET here]'
